# Build Stage
FROM node:22 AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_RECAPTCHA_SITE_KEY
ARG VITE_PASSWORD_RESET_REDIRECT
ARG VITE_WELCOME_REDIRECT
ARG VITE_API_BASE_URL
ARG VITE_NEWS_API_KEY

ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_RECAPTCHA_SITE_KEY=$VITE_RECAPTCHA_SITE_KEY
ENV VITE_PASSWORD_RESET_REDIRECT=$VITE_PASSWORD_RESET_REDIRECT
ENV VITE_WELCOME_REDIRECT=$VITE_WELCOME_REDIRECT
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_NEWS_API_KEY=$VITE_NEWS_API_KEY

RUN npm run build

# Serve Using Nginx
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]